before:
  hooks:
    - go mod download

env:
  - GO111MODULE=on

builds:
  -
    id: server-mac
    dir: server
    ldflags:
      - -s -w
    binary: server
    env:
      - CGO_ENABLED=1
      - CC=clang
      - CXX=clang++
    goarch:
      - amd64
    goos:
      - darwin

archives:
  - replacements:
      darwin: Darwin
      amd64: x86_64

checksum:
  name_template: 'checksums-macos.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
