name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - name: release dry run
        run: make release-dry-run
      - name: Setup github token.
        run: echo 'GITHUB_TOKEN=${{secrets.GH_TOKEN}}' > .release-env
      - name: release publish
        run: make release
